build:
    environment:
        php:
            version: 5.5.9
    tests: true

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_mess_detector: true
    php_cs_fixer: true
    sensiolabs_security_checker: true
    php_cpd: true
    php_loc: true
    php_hhvm: true
    php_code_sniffer: true
    php_sim: true
    php_changetracking: true
    php_pdepend: true
    php_analyzer: true

